receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
  
exporters:
  embeddingexporter:
    verbosity: detailed
    embedding:
      key: ""
      endpoint: "https://rg-openai-sandbox.openai.azure.com/"
    persistence:
      host     : "localhost"
      port     : "6969"
      password : "toeter"
  logging:
    verbosity: detailed

service:
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [embeddingexporter]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [embeddingexporter]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: 
        - embeddingexporter
        #- logging